<?php
Mage::getSingleton('customer/session')->setLiftgateneeded(null);
Mage::getSingleton('customer/session')->setResidential(null);
?>
<?php $this->setPriceDataObject($this->getSource()) ?>
<?php if ((float) $this->getSource()->getLiftgateneeded()): ?>
    <tr>
        <td class="label"><?php echo 'Liftgate' ?></td>
        <td>
            <?php echo $this->displayPrices($this->getSource()->getBaseFeeAmount(), $this->getSource()->getLiftgateneeded()); ?>
        </td>
    </tr>
<?php endif; ?>
<?php if ((float) $this->getSource()->getResidential()): ?>
    <tr>
        <td class="label"><?php echo 'Residential' ?></td>
        <td>
            <?php echo $this->displayPrices($this->getSource()->getBaseFeeAmount(), $this->getSource()->getResidential()); ?>
        </td>
    </tr>
<?php endif; ?>